const friends = [
  {
    id: 1,
    username: "john_doe",
    email: "john.doe@example.com",
    password: "password123",
    profilePic: "https://gratisography.com/wp-content/uploads/2023/06/gratisography-strange-world-free-stock-photo-800x525.jpg",
    isFollowing: false,
    points: 1400,
  },
  {
    id: 2,
    username: "jane_smith",
    email: "jane.smith@example.com",
    password: "password123",
    profilePic: "https://gratisography.com/wp-content/uploads/2023/06/gratisography-rabbit-hat-free-stock-photo-800x525.jpg",
    isFollowing: false,
    points: 1200,
  },
  {
    id: 3,
    username: "mike_williams",
    email: "mike.williams@example.com",
    password: "password123",
    profilePic: "https://gratisography.com/wp-content/uploads/2023/06/gratisography-strange-world-free-stock-photo-800x525.jpg",
    isFollowing: false,
    points: 1200,
  },
  {
    id: 4,
    username: "emily_jones",
    email: "emily.jones@example.com",
    password: "password123",
    profilePic: "https://example.com/images/emily.jpg",
    isFollowing: false,
    points: 1200,
  },
  {
    id: 5,
    username: "david_brown",
    email: "david.brown@example.com",
    password: "password123",
    profilePic: "https://example.com/images/david.jpg",
    isFollowing: false,
    points: 1200,
  },
  {
    id: 6,
    username: "sophia_white",
    email: "sophia.white@example.com",
    password: "password123",
    profilePic: "https://example.com/images/sophia.jpg",
    isFollowing: false,
    points: 1200,
  },
  {
    id: 7,
    username: "chris_green",
    email: "chris.green@example.com",
    password: "password123",
    profilePic: "https://example.com/images/chris.jpg",
    isFollowing: false,
    points: 1200,
  },
  {
    id: 8,
    username: "sam",
    email: "sam@example.com",
    password: "password123",
    profilePic: "https://example.com/images/chris.jpg",
    isFollowing: false,
    points: 1200,
  },
  {
    id: 9,
    username: "olivia_black",
    email: "olivia.black@example.com",
    password: "password123",
    profilePic: "https://example.com/images/olivia.jpg",
    isFollowing: false,
    points: 1200,
  },
  {
    id: 10,
    username: "daniel_gray",
    email: "daniel.gray@example.com",
    password: "password123",
    profilePic: "https://example.com/images/daniel.jpg",
    isFollowing: false,
    points: 1200,
  },
  {
    id: 11,
    username: "ava_silver",
    email: "ava.silver@example.com",
    password: "password123",
    profilePic: "https://example.com/images/ava.jpg",
    isFollowing: false,
    points: 1200,
  },
];

export default friends;
